# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "packetoio/amazon-corretto"
name    = "Paketo Amazon Corretto Buildpack"
version = "{{.Version}}"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata.default-versions]
jdk = "11.*"
jre = "11.*"

[[metadata.dependencies]]
id      = "jdk"
name    = "Corretto JDK"
version = "8.242.08"
uri     = "https://corretto.aws/downloads/resources/8.242.08.1/amazon-corretto-8.242.08.1-linux-x64.tar.gz"
sha256  = "e302fbd2d7354a2a8c5fa7491f4de1d73967104078da9671abada260b2f02fcd"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

[[metadata.dependencies]]
id      = "jdk"
name    = "Corretto JDK"
version = "11.0.6"
uri     = "https://corretto.aws/downloads/resources/11.0.6.10.1/amazon-corretto-11.0.6.10.1-linux-x64.tar.gz"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "1.16.0"
uri     = "https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so"
sha256  = "a3092627b082cb3cdbbe4b255d35687126aa604e6b613dcda33be9f7e1277162"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "memory-calculator"
name    = "Memory Calculator"
version = "4.0.0"
uri     = "https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-4.0.0.tgz"
sha256  = "90d40eab6959a7b4059c6409c4505040e8a04f75a481f7282e53430df3edda3e"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/java-buildpack-memory-calculator/blob/master/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/class-counter",
  "bin/detect",
  "bin/link-local-dns",
  "bin/security-providers-configurer",
  "buildpack.toml",
]
